default_platform :ios

fastlane_require "dotenv"

before_all do
    #Dotenv.load ".env.production"
	sh 'mkdir ../reports || true'
	sh 'mkdir ../dist || true'
end


desc "Install pod dependencies"
lane :podInstall do
     cocoapods(
             podfile: ENV["PODFILE_PATH"],
             use_bundle_exec: false
             )
end
      
      
# Fastlane runs all built in actions from one directory above where the Fastfile lives
# so make sure all the paths are relative in that regard.
desc "Does a static analysis of the project. Configure the options in .swiftlint.yml"
lane :lint do
	swiftlint(
		mode: :lint,
		output_file: 'reports/swiftlint.txt',
 		config_file: 'fastlane/.swiftlint.yml'
	)
end

desc "Runs all the unit tests and UI Tests"
desc "Configure the .env.default file in this directory before you run the test or build lanes."
desc "Info on the .env files and how to use them can be found here: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md#environment-variables"
lane :test do
	# Run tests
	test_args = {
		scheme: ENV["SCHEME"],
		clean: true,
		code_coverage: true,
		output_types: "html, junit",
		output_directory: "reports"
	}
	if ENV["WORKSPACE"]
		test_args[:workspace] = ENV["WORKSPACE"]
	else
		test_args[:project] = ENV["PROJECT"]
	end

	scan(test_args)

	# Generate code coverage report
	code_cov_args = {
		scheme: ENV["SCHEME"],
		proj:  ENV["PROJECT"],
		cobertura_xml: true,
		output_directory: "reports/"
	}
	if ENV["WORKSPACE"]
		code_cov_args[:workspace] =  ENV["WORKSPACE"]
	end

	slather(code_cov_args)
end

desc "Builds the project and produces an .ipa. Pass in the build_number as a param. Default is 1."
desc "Docs on how to pass in parameters are here: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md#passing-parameters"
lane :build do |options|

  update_project_provisioning(
    xcodeproj: ENV["PROJECT"],
    profile: ENV["PATH_PROVISIONING_PROFILE"], # optional if you use sigh
    target_filter: ENV["SCHEME"], # matches name or type of a target
    build_configuration: ENV["CONFIGURATION"],
    code_signing_identity: ENV["CERTIFICATE"] # optionally specify the codesigning identity
  )
  
	# Set default build number for local builds
	build_number = "1"

	# Read in value in case the user has specified input params
	if options[:build_number]
		build_number = options[:build_number]
	end

	increment_build_number(
  		build_number: build_number,
  		xcodeproj: ENV["PROJECT"]
	)

	increment_version_number(
 		version_number: ENV["VERSION"],
  		xcodeproj: ENV["PROJECT"]
	)

	# Build additional args to xcodebuild
	xcodeargs = "PRODUCT_BUNDLE_IDENTIFIER=" + ENV["BUNDLE_ID"]
	if ENV["PROVISIONING_PROFILE"]
		xcodeargs = xcodeargs + " " + "PROVISIONING_PROFILE=" + ENV["PROVISIONING_PROFILE"]
	end

	args = {
    export_options: {
       signingStyle: "automatic",
       provisioningProfiles: {
               ENV["BUNDLE_ID"] => ENV["PROVISIONING_PROFILE"],
             }
      },
		scheme: ENV["SCHEME"],
		clean: true,
    toolchain: ENV["BUNDLE_ID"],
		output_directory: ENV["OUTPUT_DIRECTORY"],
    export_method: ENV["EXPORT_METHOD"],
		output_name: ENV["PRODUCT_NAME"].dup, # Fastlane probably modifies this string under the hood, so the .dup is needed to make it mutable.
		codesigning_identity: ENV["CERTIFICATE"],
    include_symbols: true,
    configuration:ENV["CONFIGURATION"],
		xcargs: xcodeargs
	}

	if ENV["WORKSPACE"]
		args[:workspace] = ENV["WORKSPACE"]
	else
		args[:project] = ENV["PROJECT"]
	end

  build_app(
    workspace: ENV["WORKSPACE"],
    output_directory: "./dist",
      export_method: "app-store",
      scheme: ENV["SCHEME"]
    )
	#gym(args)
end

desc "Deploys the built IPA and symbols on Testflight"
lane :deploy do
  ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
   pilot(
   ipa:"dist/" + ENV["PRODUCT_NAME"],
   skip_waiting_for_build_processing:true,
   distribute_external: false
   )
end
